server:
  port: 8081

spring:
  application:
    name: iam
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/demo}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uris:
            sso: ${JWK_SSO_URL:http://172.31.2.120:8070/realms/z113-qa/protocol/openid-connect/certs}
            internal: ${JWK_INTERNAL_URL:http://localhost:8081/api/certificate/.well-known/jwks.json}

app:
  iam:
    internal-url: http://localhost:8081

security:
  authentication:
    jwt:
      key-store: tracking.jks
      key-store-password: dinh1008
      key-alias: tracking